// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddns

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetCurrentIPv4 provides a mock function for the type MockClient
func (_mock *MockClient) GetCurrentIPv4(ctx context.Context) (net.IP, string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentIPv4")
	}

	var r0 net.IP
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (net.IP, string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) net.IP); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_GetCurrentIPv4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentIPv4'
type MockClient_GetCurrentIPv4_Call struct {
	*mock.Call
}

// GetCurrentIPv4 is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetCurrentIPv4(ctx interface{}) *MockClient_GetCurrentIPv4_Call {
	return &MockClient_GetCurrentIPv4_Call{Call: _e.mock.On("GetCurrentIPv4", ctx)}
}

func (_c *MockClient_GetCurrentIPv4_Call) Run(run func(ctx context.Context)) *MockClient_GetCurrentIPv4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetCurrentIPv4_Call) Return(ip net.IP, recordID string, err error) *MockClient_GetCurrentIPv4_Call {
	_c.Call.Return(ip, recordID, err)
	return _c
}

func (_c *MockClient_GetCurrentIPv4_Call) RunAndReturn(run func(ctx context.Context) (net.IP, string, error)) *MockClient_GetCurrentIPv4_Call {
	_c.Call.Return(run)
	return _c
}

// SetARecordIP provides a mock function for the type MockClient
func (_mock *MockClient) SetARecordIP(ctx context.Context, ip net.IP, recordID string) error {
	ret := _mock.Called(ctx, ip, recordID)

	if len(ret) == 0 {
		panic("no return value specified for SetARecordIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, net.IP, string) error); ok {
		r0 = returnFunc(ctx, ip, recordID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetARecordIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetARecordIP'
type MockClient_SetARecordIP_Call struct {
	*mock.Call
}

// SetARecordIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ip net.IP
//   - recordID string
func (_e *MockClient_Expecter) SetARecordIP(ctx interface{}, ip interface{}, recordID interface{}) *MockClient_SetARecordIP_Call {
	return &MockClient_SetARecordIP_Call{Call: _e.mock.On("SetARecordIP", ctx, ip, recordID)}
}

func (_c *MockClient_SetARecordIP_Call) Run(run func(ctx context.Context, ip net.IP, recordID string)) *MockClient_SetARecordIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 net.IP
		if args[1] != nil {
			arg1 = args[1].(net.IP)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_SetARecordIP_Call) Return(err error) *MockClient_SetARecordIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetARecordIP_Call) RunAndReturn(run func(ctx context.Context, ip net.IP, recordID string) error) *MockClient_SetARecordIP_Call {
	_c.Call.Return(run)
	return _c
}
